name: get_data_from_iss

# Schedule the run
on:
  workflow_dispatch:
  schedule:
    - cron:  '*/10 * * * *'

jobs:
  # Set the job key.
  scrape-data:
    # Name of the Job
    name: Scrape data
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Check out a copy of this repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Clean staging area
      - name: Clean staging area
        run: rm data/staging/*

      # Get data
      - name: Get data
        run: ./get_data.sh

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Parse them all
      - name: Parse them all
        run: |
          python parser.py

      # Commit & Push
      - name: Commit a new report (if necessary)
        run: |
          now=$(date +'%d-%m-%Y')
          echo "Checking data on: ${now}"
          mkdir data/${now} || true
          cp data/staging/* data/${now}
          git config --global user.name 'GitHub Actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am "Refresh data on: ${now}" || true
          git push
        env:
          TZ: Europe/Rome
