name: test

# Schedule the run
on:
  workflow_dispatch:


jobs:
  # Set the job key.
  scrape-data:
    # Name of the Job
    name: test
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Check out a copy of this repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2


      # Commit & Push
      - name: Commit a new report (if necessary)
        run: |
          git push
        env:
          TZ: Europe/Rome
